# Generated by Django 4.0.4 on 2022-04-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cotente', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
