# Generated by Django 4.0.4 on 2022-04-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_project_image_alter_project_cotente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='fimage',
        ),
    ]
