# Generated by Django 4.0.4 on 2022-04-25 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_project_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project',
        ),
        migrations.CreateModel(
            name='project_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.projects')),
            ],
        ),
    ]
