# Generated by Django 4.0.4 on 2022-04-25 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_project_project_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cotente', models.TextField(max_length=1000)),
                ('fimage', models.ImageField(default=0, upload_to='photos/%y/%m/%d')),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='fimage',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cotente',
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project_image',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.project'),
        ),
        migrations.DeleteModel(
            name='projects',
        ),
        migrations.AddField(
            model_name='main_project',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.project'),
        ),
    ]
