# Generated by Django 4.0.4 on 2022-04-25 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0008_remove_project_image_project_delete_main_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default=0, max_length=150)),
                ('image', models.ImageField(default=0, upload_to='photos/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='project_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.project')),
            ],
        ),
        migrations.CreateModel(
            name='main_project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cotente', models.TextField(max_length=1000)),
                ('fimage', models.ImageField(default=0, upload_to='photos/%y/%m/%d')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.project')),
            ],
        ),
    ]
