# Generated by Django 4.0.4 on 2022-04-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_project',
            name='fimage',
            field=models.ImageField(upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
