# Generated by Django 4.0.4 on 2022-04-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_main_project_fimage_alter_project_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_project',
            old_name='project',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project_image',
            old_name='project',
            new_name='name',
        ),
    ]
