# Generated by Django 4.0.4 on 2022-04-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_rename_name_main_project_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
