# Generated by Django 4.0.4 on 2022-04-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_image',
            name='id_n',
            field=models.IntegerField(default=0),
        ),
    ]
