# Generated by Django 4.0.4 on 2022-04-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='frist_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
