# Generated by Django 4.0.4 on 2022-04-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_contact_frist_name_alter_contact_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
