# Generated by Django 4.0.4 on 2022-04-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_project',
            name='cotente',
            field=models.TextField(default=0, max_length=1500),
        ),
    ]
